In [28]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
data=pd.read_csv("C:/career 2026-27/projects/customer_churn_preprocessing/data/customer_churn_dataset-testing-master.csv")

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         64374 non-null  int64
 1   Age                64374 non-null  int64
 2   Gender             64374 non-null  object
 3   Tenure             64374 non-null  int64
 4   Usage Frequency    64374 non-null  int64
 5   Support Calls      64374 non-null  int64
 6   Payment Delay      64374 non-null  int64
 7   Subscription Type  64374 non-null  object
 8   Contract Length    64374 non-null  object
 9   Total Spend        64374 non-null  int64
 10  Last Interaction   64374 non-null  int64
 11  Churn              64374 non-null  int64
dtypes: int64(9), object(3)
memory usage: 5.9+ MB

In [30]:
data.shape

(64374, 12)

In [31]:
data.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [32]:
data.describe()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000
mean,32187.500000,41.970982,31.994827,15.080234,5.400690,17.133952,541.023379,15.498850,0.473685
std,18583.317451,13.924911,17.098234,8.816470,3.114005,8.852211,260.874809,8.638436,0.499311
min,1.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,16094.250000,30.000000,18.000000,7.000000,3.000000,10.000000,313.000000,8.000000,0.000000
50%,32187.500000,42.000000,33.000000,15.000000,6.000000,19.000000,534.000000,15.000000,0.000000
75%,48280.750000,54.000000,47.000000,23.000000,8.000000,25.000000,768.000000,23.000000,1.000000
max,64374.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [55]:
#check null values
data.isnull().sum()

CustomerID                    0
Age                           0
Gender                        0
Tenure                        0
Usage Frequency               0
Support Calls                 0
Payment Delay                 0
Total Spend                   0
Last Interaction              0
Churn                         0
Subscription Type_Premium     0
Subscription Type_Standard    0
Contract Length_Monthly       0
Contract Length_Quarterly     0
dtype: int64

In [53]:
#check duplicates
print(data.duplicated().sum())

0

In [54]:
#identify categorical columns
data.select_dtypes(include='object').columns

Index(['Gender'], dtype='object')

In [51]:
#encode categorical variables
pd.get_dummies(data, columns=['Gender'], drop_first=True)

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly,Gender_Male
0,1,22,25,14,4,27,598,9,1,False,False,True,False,False
1,2,41,28,28,7,13,584,20,0,False,True,True,False,False
2,3,47,27,10,2,29,757,21,0,True,False,False,False,True
3,4,35,9,12,5,17,232,18,0,True,False,False,True,True
4,5,53,58,24,9,2,533,18,0,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64369,64370,45,33,12,6,21,947,14,1,False,False,False,True,False
64370,64371,37,6,1,5,22,923,9,1,False,True,False,False,True
64371,64372,25,39,14,8,30,327,20,1,True,False,True,False,True
64372,64373,50,18,19,7,22,540,13,1,False,True,True,False,False
64373,64374,52,45,15,9,25,696,22,1,False,True,True,False,False

In [37]:
data = pd.get_dummies(data,
                    columns=['Subscription Type'],
                    drop_first=True)

In [38]:
data = pd.get_dummies(data,
                    columns=['Contract Length'],
                    drop_first=True)

In [39]:
data.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,1,22,Female,25,14,4,27,598,9,1,False,False,True,False
1,2,41,Female,28,28,7,13,584,20,0,False,True,True,False
2,3,47,Male,27,10,2,29,757,21,0,True,False,False,False
3,4,35,Male,9,12,5,17,232,18,0,True,False,False,True
4,5,53,Female,58,24,9,2,533,18,0,False,True,False,False

In [40]:
print(data.columns)

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Total Spend', 'Last Interaction',
       'Churn', 'Subscription Type_Premium', 'Subscription Type_Standard',
       'Contract Length_Monthly', 'Contract Length_Quarterly'],
      dtype='object')

In [50]:
#seperate features and target
X = data.drop(['CustomerID', 'Churn'], axis=1)
y = data['Churn']

In [49]:
#scaling
num_cols = [
    'Age',
    'Tenure',
    'Usage Frequency',
    'Support Calls',
    'Payment Delay',
    'Total Spend',
    'Last Interaction'
]

scaler = StandardScaler()

X[num_cols] = scaler.fit_transform(X[num_cols])

In [48]:
#Train and test split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [44]:
print(X_train.shape)

(51499, 12)

In [45]:
print(X_test.shape)

(12875, 12)

In [46]:
print(y_train.shape)

(51499,)

In [47]:
print(y_test.shape)

(12875,)